import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'fr' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.explore': 'Explore',
    'nav.bookings': 'My Bookings',
    'nav.account': 'My Account',
    'nav.signin': 'Login',
    'nav.signup': 'Create Account',
    'nav.signout': 'Sign Out',
    'nav.profile': 'Profile',

    // Hero Section
    'hero.title': 'Book Your Appointment with the Best Barbers',
    'hero.description': 'Discover nearby barbers, view their work, and book your appointment easily',
    'hero.search.salon': 'Search for a barber or salon...',
    'hero.search.location': 'City or Region',
    'hero.search.button': 'Search Now',
    'hero.search.nearby': 'Nearby Barbers',

    // Filters
    'filters.title': 'Filters',
    'filters.location': 'Location',
    'filters.location.placeholder': 'Enter city or area',
    'filters.quick': 'Quick Filters',
    'filters.nearby': 'Nearby',
    'filters.open': 'Open Now',
    'filters.rated': 'Highly Rated',
    'filters.vip': 'VIP Service',
    'filters.gender': 'Gender Preference',
    'filters.services': 'Services',
    'filters.price': 'Price Range',
    'filters.rating': 'Minimum Rating',
    'filters.apply': 'Apply Filters',
    'filters.clear': 'Clear All',
    'filter.all': 'All Salons',
    'filter.men': 'Men\'s Barbershops',
    'filter.women': 'Women\'s Salons',
    'filter.unisex': 'Mixed Salons',
    'filter.open': 'Open Now',
    'filter.vip': 'VIP Only',
    'filter.sort': 'Sort by Distance',

    // Salon Cards
    'salon.vip': 'VIP',
    'salon.open': 'Open until',
    'salon.closed': 'Closed',
    'salon.men': 'men',
    'salon.women': 'women',
    'salon.mixed': 'Mixed',
    'salon.starting': 'Starting from',
    'salon.next': 'Next available',
    'salon.book': 'Book Now',
    'salon.details': 'View Details',
    'salon.gallery': 'Work Gallery',

    // Salon Grid
    'grid.title': 'Discover',
    'grid.title.highlight': 'Premium Salons',
    'grid.description': 'Find the perfect salon or barbershop near you. Professional services, expert stylists, and unbeatable convenience.',
    'grid.found': 'salons found',
    'grid.sorted': 'Sorted by: Distance',
    'grid.load': 'Load More Salons',

    // Payment Methods
    'payment.title': 'Payment Methods',
    'payment.baridi': 'Baridi Mob',
    'payment.baridi.desc': 'Pay with Algerian mobile money',
    'payment.visa': 'Visa Card',
    'payment.mastercard': 'MasterCard',
    'payment.card.desc': 'International card payment',
    'payment.paypal': 'PayPal',
    'payment.paypal.desc': 'Secure online payment',
    'payment.after': 'Pay After Service',
    'payment.after.desc': 'Cash payment after haircut',
    'payment.select': 'Select Payment Method',

    // Footer
    'footer.about': 'About Us',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.contact': 'Contact Us',
    'footer.download': 'Download App',
    'footer.rights': 'All rights reserved',
    'footer.description': 'Your trusted platform for professional barber and beauty services',

    // App Download
    'download.title': 'Download Our App',
    'download.subtitle': 'Book appointments on the go',
    'download.android': 'Get it on Google Play',
    'download.ios': 'Download on App Store',
    'download.description': 'Experience seamless booking with our mobile app. Available for Android and iOS.',

    // Authentication
    'auth.welcome': 'Welcome to barberlinkshop',
    'auth.subtitle': 'Connect with professional barbers',
    'auth.signin': 'Sign In',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.email.placeholder': 'Enter your email',
    'auth.password': 'Password',
    'auth.password.placeholder': 'Enter your password',
    'auth.fullname': 'Full Name',
    'auth.fullname.placeholder': 'Enter your full name',
    'auth.phone': 'Phone Number',
    'auth.phone.placeholder': 'Enter your phone number',
    'auth.usertype': 'I am a',
    'auth.usertype.customer': 'Customer',
    'auth.usertype.barber': 'Barber',
    'auth.loading': 'Loading...',
    'auth.error': 'Authentication Error',
    'auth.signup.success': 'Account created successfully',
    'auth.signup.success.desc': 'Welcome to barberlinkshop!',

    // Barber Profile
    'barber.notfound': 'Barber not found',
    'barber.homevisit': 'Home Visit',
    'barber.book': 'Book Appointment',
    'barber.whatsapp': 'WhatsApp',
    'barber.favorite': 'Favorite',
    'barber.share': 'Share',
    'barber.services': 'Services',
    'barber.gallery': 'Gallery',
    'barber.reviews': 'Reviews',
    'barber.minutes': 'min',
    'salon.staff': 'Staff & Chairs',
    'staff.book': 'Book with',
    'booking.notspecified': 'Any Available',
    'currency': 'DZD',
    'loading': 'Loading...',
    'error': 'Error',

    // Services
    'service.haircut': 'Haircut',
    'service.beard': 'Beard Trim',
    'service.kids': 'Kids Haircut',
    'service.shave': 'Traditional Shave',
    'service.coloring': 'Hair Coloring',
    'service.styling': 'Hair Styling',
    'service.keratin': 'Keratin Treatment',
    'service.protein': 'Protein Treatment',
    'service.facial': 'Facial Treatment',
    'service.massage': 'Head Massage',
    'service.home': 'VIP Home Service',

    // Salon Types
    'salon.type.men': 'Men',
    'salon.type.women': 'Women',
    'salon.type.unisex': 'Unisex',

    // Contact
    'contact.call': 'Call',
    'contact.whatsapp': 'WhatsApp',
    'contact.chat': 'Chat Now',
    'store.title': 'Store',
    'store.buy': 'Buy Now',
    'store.comingsoon': 'Coming Soon',
    'store.desc': 'Online store checkout is not fully active yet!',

    // Pricing
    'pricing.title': 'Choose Your Plan',
    'pricing.subtitle': 'Sign up now and get your first month for FREE!',
    'pricing.monthly': 'Monthly',
    'pricing.dzd': 'DZD',
    'pricing.month': '/mo',
    'pricing.basic.name': 'Basic Plan',
    'pricing.basic.desc': 'Perfect for independent professionals.',
    'pricing.basic.price': '1000',
    'pricing.basic.f1': 'Unlimited Bookings',
    'pricing.basic.f2': 'Client Management',
    'pricing.basic.f3': 'Basic Portfolio',
    'pricing.basic.f4': 'Appointment Notifications',
    'pricing.pro.name': 'Pro Plan',
    'pricing.pro.desc': 'For growing salons.',
    'pricing.pro.price': '1500',
    'pricing.pro.f1': 'Everything in Basic',
    'pricing.pro.f2': 'Integrated Digital Store',
    'pricing.pro.f3': 'AI Style & Makeup Assistant',
    'pricing.pro.f4': 'Weekly Financial Reports',
    'pricing.premium.name': 'Premium Plan',
    'pricing.premium.desc': 'Advanced tools for full automation.',
    'pricing.premium.price': '2000',
    'pricing.premium.f1': 'Everything in Pro',
    'pricing.premium.f2': 'VIP Search Placement',
    'pricing.premium.f3': 'Staff & Chairs Management',
    'pricing.premium.f4': 'Detailed Monthly Invoices',
    'pricing.button.start': 'Start 1 Month Free Trial',

    // Testimonials
    'testi.title': 'What Our Users Say',
    'testi.sub': 'Join thousands of satisfied salon owners and clients.',
    'testi.1.text': 'barberlinkshop transformed my business! The AI stylist brings so many new female clients, and the automated weekly reports save me hours of accounting.',
    'testi.1.name': 'Sarah L.',
    'testi.1.role': 'Salon Owner',
    'testi.2.text': 'I manage 4 chairs in my barber shop. The platform handles all bookings seamlessly and sends SMS notifications to clients automatically.',
    'testi.2.name': 'Ahmed B.',
    'testi.2.role': 'Master Barber',
    'testi.3.text': 'As a customer, I love how easy it is to find a salon, choose my specific barber, and buy my favorite beard oil directly from their digital store.',
    'testi.3.name': 'Karim M.',
    'testi.3.role': 'Client',

    // AI Stylist
    'ai.stylist.title': 'AI Style & Makeup Assistant',
    'ai.stylist.desc': 'Upload your photo and let AI recommend the perfect hairstyle and makeup tailored for you!',
    'ai.stylist.upload': 'Upload Photo',
    'ai.stylist.men': 'Men (Hair & Beard)',
    'ai.stylist.women': 'Women (Hair & Makeup)',
    'ai.stylist.generate': 'Generate Styles',
    'ai.stylist.result': 'Your AI Recommendations:',
    'ai.keratin': 'Keratin & Protein treatments',
    'ai.coloring': 'Hair Coloring & Highlights',
    'ai.makeup': 'Professional Makeup',

    // Theme
    'theme.light': 'Light Mode',
    'theme.dark': 'Dark Mode',
    'theme.toggle': 'Toggle Theme',

    // Booking Modal
    'booking.title': 'Book Appointment',
    'booking.service': 'Select Service',
    'booking.service.select': 'Choose a service',
    'booking.service.none': 'No service selected',
    'booking.date': 'Select Date',
    'booking.date.select': 'Pick a date',
    'booking.time': 'Select Time',
    'booking.payment': 'Payment Method',
    'booking.total': 'Total',
    'booking.confirm': 'Confirm Booking',
    'booking.cancel': 'Cancel',
    'payment.electronic': 'Electronic Payment',
    'payment.after.visit': 'Pay on Arrival',
    'salon.reviews': 'reviews',

    // Dashboards & Profiles
    'dashboard.title.customer': 'My Bookings',
    'dashboard.title.barber': 'Barber Dashboard',
    'dashboard.customer.empty': 'You have no bookings yet. Explore barbers to book your first appointment!',
    'dashboard.explore': 'Explore Barbers',
    'dashboard.review.write': 'Write a Review',
    'dashboard.review.rate': 'Rate Your Experience',
    'dashboard.review.submit': 'Submit Review',
    'dashboard.view.profile': 'View Profile',
    'dashboard.services.management': 'Service Management',
    'dashboard.services.desc': 'Manage your services and prices',
    'dashboard.service.add': 'Add Service',
    'dashboard.service.edit': 'Edit Service',
    'dashboard.service.update': 'Update Service',
    'dashboard.service.name.ar': 'Service Name (Arabic)',
    'dashboard.service.name.en': 'Service Name (English)',
    'dashboard.service.name.fr': 'Service Name (French)',
    'dashboard.service.desc.ar': 'Description (Arabic)',
    'dashboard.service.desc.en': 'Description (English)',
    'dashboard.service.desc.fr': 'Description (French)',
    'dashboard.service.price': 'Price (DZD)',
    'dashboard.service.duration': 'Duration (minutes)',
    'dashboard.tabs.services': 'Services',
    'dashboard.tabs.bookings': 'Bookings',
    'dashboard.tabs.profile': 'Profile & QR',
    'dashboard.tabs.finance': 'Finance',
    'dashboard.services.empty': 'No services yet',
    'dashboard.services.first': 'Add Your First Service',
    'dashboard.requests.online': 'Online Requests',
    'dashboard.requests.empty': 'No appointments yet.',
    'dashboard.requests.accept': 'Accept',
    'dashboard.requests.reject': 'Reject',
    'dashboard.requests.complete': 'Mark Completed',
    'dashboard.payment.online': 'Paid Online',
    'dashboard.payment.salon': 'Pay at Salon',
    'dashboard.walkin.title': 'Manual Walk-in Booking',
    'dashboard.walkin.desc': 'Add appointments for off-platform customers or walk-ins',
    'dashboard.walkin.add': 'Add Walk-in Appointment',
    'dashboard.qr.title': 'Your Salon QR Code',
    'dashboard.qr.desc': 'Share this QR code in your salon for quick bookings',
    'dashboard.gallery.title': 'Work Gallery',
    'dashboard.gallery.desc': 'Upload photos and videos of your best work to attract more clients',
    'dashboard.gallery.upload': 'Upload Photo/Video',
    'dashboard.finance.earnings': 'Total Earnings',
    'dashboard.finance.expenses': 'Total Expenses',
    'dashboard.finance.profit': 'Net Profit',
    'dashboard.finance.add': 'Add New Expense',
    'dashboard.finance.expense.desc': 'Track your barbering supplies, salon rent, and daily expenses.',
    'dashboard.finance.expense.name': 'Expense Name',
    'dashboard.finance.expense.amount': 'Amount (DZD)',
    'dashboard.finance.weekly': 'Weekly Revenue',
    'dashboard.finance.recent': 'Recent Expenses',

    // Notifications
    'notification.upcoming.30m': 'Appointment in 30 minutes!',
    'notification.upcoming.15m': 'Appointment in 15 minutes!',
    'notification.upcoming.msg': 'You have an appointment scheduled with',
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.explore': 'Explorer',
    'nav.bookings': 'Mes Réservations',
    'nav.account': 'Mon Compte',
    'nav.signin': 'Connexion',
    'nav.signup': 'Créer un Compte',
    'nav.signout': 'Déconnexion',
    'nav.profile': 'Profil',

    // Hero Section
    'hero.title': 'Réservez Votre Rendez-vous avec les Meilleurs Coiffeurs',
    'hero.description': 'Découvrez les coiffeurs à proximité, consultez leurs travaux et réservez facilement',
    'hero.search.salon': 'Rechercher un coiffeur ou un salon...',
    'hero.search.location': 'Ville ou Région',
    'hero.search.button': 'Rechercher',
    'hero.search.nearby': 'Coiffeurs à Proximité',

    // Filters
    'filters.title': 'Filtres',
    'filters.location': 'Emplacement',
    'filters.location.placeholder': 'Entrez ville ou région',
    'filters.quick': 'Filtres Rapides',
    'filters.nearby': 'À Proximité',
    'filters.open': 'Ouvert Maintenant',
    'filters.rated': 'Bien Notés',
    'filters.vip': 'Service VIP',
    'filters.gender': 'Préférence de Genre',
    'filters.services': 'Services',
    'filters.price': 'Gamme de Prix',
    'filters.rating': 'Note Minimum',
    'filters.apply': 'Appliquer les Filtres',
    'filters.clear': 'Tout Effacer',
    'filter.all': 'Tous les Salons',
    'filter.men': 'Coiffeurs Hommes',
    'filter.women': 'Salons Femmes',
    'filter.unisex': 'Salons Mixtes',
    'filter.open': 'Ouvert Maintenant',
    'filter.vip': 'VIP Seulement',
    'filter.sort': 'Trier par Distance',

    // Salon Cards
    'salon.vip': 'VIP',
    'salon.open': 'Ouvert jusqu\'à',
    'salon.closed': 'Fermé',
    'salon.men': 'hommes',
    'salon.women': 'femmes',
    'salon.mixed': 'Mixte',
    'salon.starting': 'À partir de',
    'salon.next': 'Prochaine disponibilité',
    'salon.book': 'Réserver',
    'salon.details': 'Voir Détails',
    'salon.gallery': 'Galerie de Travaux',

    // Salon Grid
    'grid.title': 'Découvrez des',
    'grid.title.highlight': 'Salons Premium',
    'grid.description': 'Trouvez le salon parfait près de chez vous. Services professionnels, stylistes experts.',
    'grid.found': 'salons trouvés',
    'grid.sorted': 'Trié par: Distance',
    'grid.load': 'Charger Plus de Salons',

    // Payment Methods
    'payment.title': 'Méthodes de Paiement',
    'payment.baridi': 'Baridi Mob',
    'payment.baridi.desc': 'Paiement mobile algérien',
    'payment.visa': 'Carte Visa',
    'payment.mastercard': 'MasterCard',
    'payment.card.desc': 'Paiement par carte internationale',
    'payment.paypal': 'PayPal',
    'payment.paypal.desc': 'Paiement en ligne sécurisé',
    'payment.after': 'Payer Après Service',
    'payment.after.desc': 'Paiement en espèces après coiffure',
    'payment.select': 'Choisir Méthode de Paiement',

    // Footer
    'footer.about': 'À Propos',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.terms': 'Conditions d\'Utilisation',
    'footer.contact': 'Contactez-nous',
    'footer.download': 'Télécharger l\'App',
    'footer.rights': 'Tous droits réservés',
    'footer.description': 'Votre plateforme de confiance pour les services de coiffure professionnels',

    // App Download
    'download.title': 'Téléchargez Notre Application',
    'download.subtitle': 'Réservez en déplacement',
    'download.android': 'Disponible sur Google Play',
    'download.ios': 'Télécharger sur App Store',
    'download.description': 'Profitez d\'une réservation fluide avec notre application mobile. Disponible pour Android et iOS.',

    // Authentication
    'auth.welcome': 'Bienvenue sur barberlinkshop',
    'auth.subtitle': 'Connectez-vous avec des coiffeurs professionnels',
    'auth.signin': 'Se Connecter',
    'auth.signup': 'S\'inscrire',
    'auth.email': 'Email',
    'auth.email.placeholder': 'Entrez votre email',
    'auth.password': 'Mot de passe',
    'auth.password.placeholder': 'Entrez votre mot de passe',
    'auth.fullname': 'Nom Complet',
    'auth.fullname.placeholder': 'Entrez votre nom complet',
    'auth.phone': 'Numéro de Téléphone',
    'auth.phone.placeholder': 'Entrez votre numéro',
    'auth.usertype': 'Je suis',
    'auth.usertype.customer': 'Client',
    'auth.usertype.barber': 'Coiffeur',
    'auth.loading': 'Chargement...',
    'auth.error': 'Erreur d\'authentification',
    'auth.signup.success': 'Compte créé avec succès',
    'auth.signup.success.desc': 'Bienvenue sur barberlinkshop!',

    // Barber Profile
    'barber.notfound': 'Coiffeur introuvable',
    'barber.homevisit': 'Visite à domicile',
    'barber.book': 'Réserver',
    'barber.whatsapp': 'WhatsApp',
    'barber.favorite': 'Favori',
    'barber.share': 'Partager',
    'barber.services': 'Services',
    'barber.gallery': 'Galerie',
    'barber.reviews': 'Avis',
    'barber.minutes': 'min',
    'salon.staff': 'Personnel & Chaises',
    'staff.book': 'Réserver avec',
    'booking.notspecified': 'N\'importe qui',
    'currency': 'DZD',
    'loading': 'Chargement...',
    'error': 'Erreur',

    // Services
    'service.haircut': 'Coupe de Cheveux',
    'service.beard': 'Taille de Barbe',
    'service.kids': 'Coupe Enfant',
    'service.shave': 'Rasage Traditionnel',
    'service.coloring': 'Coloration',
    'service.styling': 'Coiffage',
    'service.keratin': 'Traitement Kératine',
    'service.protein': 'Traitement Protéine',
    'service.facial': 'Soin du Visage',
    'service.massage': 'Massage Crânien',
    'service.home': 'Service VIP à Domicile',

    // Salon Types
    'salon.type.men': 'Hommes',
    'salon.type.women': 'Femmes',
    'salon.type.unisex': 'Mixte',

    // Contact
    'contact.call': 'Appeler',
    'contact.whatsapp': 'WhatsApp',
    'contact.chat': 'Discuter',
    'store.title': 'Boutique',
    'store.buy': 'Acheter Maintenant',
    'store.comingsoon': 'Bientôt Disponible',
    'store.desc': 'La caisse de la boutique en ligne n\'est pas encore active !',

    // Pricing
    'pricing.title': 'Choisissez Votre Forfait',
    'pricing.subtitle': 'Inscrivez-vous maintenant et obtenez votre premier mois GRATUIT !',
    'pricing.monthly': 'Mensuel',
    'pricing.dzd': 'DZD',
    'pricing.month': '/mois',
    'pricing.basic.name': 'Forfait Basique',
    'pricing.basic.desc': 'Parfait pour les professionnels indépendants.',
    'pricing.basic.price': '1000',
    'pricing.basic.f1': 'Réservations Illimitées',
    'pricing.basic.f2': 'Gestion des Clients',
    'pricing.basic.f3': 'Portfolio de Base',
    'pricing.basic.f4': 'Notifications de Rendez-vous',
    'pricing.pro.name': 'Forfait Pro',
    'pricing.pro.desc': 'Pour les salons en croissance.',
    'pricing.pro.price': '1500',
    'pricing.pro.f1': 'Tout dans Basique',
    'pricing.pro.f2': 'Boutique Numérique Intégrée',
    'pricing.pro.f3': 'Assistant IA Style & Maquillage',
    'pricing.pro.f4': 'Rapports Financiers Hebdomadaires',
    'pricing.premium.name': 'Forfait Premium',
    'pricing.premium.desc': 'Outils avancés pour l\'automatisation.',
    'pricing.premium.price': '5000',
    'pricing.premium.f1': 'Tout dans Pro',
    'pricing.premium.f2': 'Placement VIP',
    'pricing.premium.f3': 'Gestions des Chaises & Personnel',
    'pricing.premium.f4': 'Factures Mensuelles Détaillées',
    'pricing.button.start': 'Commencer l\'Essai Gratuit d\'un Mois',

    // Testimonials
    'testi.title': 'Ce que disent nos utilisateurs',
    'testi.sub': 'Rejoignez des milliers de propriétaires de salons et de clients satisfaits.',
    'testi.1.text': 'barberlinkshop a transformé mon entreprise ! L\'IA m\'apporte beaucoup de nouvelles clientes et les rapports hebdomadaires automatisés me font gagner des heures de comptabilité.',
    'testi.1.name': 'Sarah L.',
    'testi.1.role': 'Propriétaire de Salon',
    'testi.2.text': 'Je gère 4 chaises dans mon salon. La plateforme gère parfaitement toutes les réservations et envoie des notifications SMS automatiques aux clients.',
    'testi.2.name': 'Ahmed B.',
    'testi.2.role': 'Maître Barbier',
    'testi.3.text': 'En tant que client, j\'adore la facilité de trouver un salon, de choisir mon barbier spécifique et d\'acheter mon huile à barbe préférée directement dans leur boutique.',
    'testi.3.name': 'Karim M.',
    'testi.3.role': 'Client',

    // AI Stylist
    'ai.stylist.title': 'Assistant de Style & Maquillage IA',
    'ai.stylist.desc': 'Téléchargez votre photo et laissez l\'IA vous recommander la coiffure et le maquillage parfaits !',
    'ai.stylist.upload': 'Télécharger une Photo',
    'ai.stylist.men': 'Hommes (Cheveux & Barbe)',
    'ai.stylist.women': 'Femmes (Cheveux & Maquillage)',
    'ai.stylist.generate': 'Générer des Styles',
    'ai.stylist.result': 'Vos Recommandations IA :',
    'ai.keratin': 'Traitements Kératine et Protéine',
    'ai.coloring': 'Coloration & Mèches',
    'ai.makeup': 'Maquillage Professionnel',

    // Theme
    'theme.light': 'Mode Clair',
    'theme.dark': 'Mode Sombre',
    'theme.toggle': 'Changer le Thème',

    // Booking Modal
    'booking.title': 'Réserver un Rendez-vous',
    'booking.service': 'Choisir le Service',
    'booking.service.select': 'Sélectionner un service',
    'booking.service.none': 'Aucun service sélectionné',
    'booking.date': 'Choisir la Date',
    'booking.date.select': 'Choisir une date',
    'booking.time': 'Choisir l\'Heure',
    'booking.payment': 'Méthode de Paiement',
    'booking.total': 'Total',
    'booking.confirm': 'Confirmer la Réservation',
    'booking.cancel': 'Annuler',
    'payment.electronic': 'Paiement Électronique',
    'payment.after.visit': 'Payer sur Place',
    'salon.reviews': 'avis',

    // Dashboards & Profiles
    'dashboard.title.customer': 'Mes Réservations',
    'dashboard.title.barber': 'Tableau de Bord Coiffeur',
    'dashboard.customer.empty': 'Vous n\'avez pas encore de réservations. Explorez les coiffeurs pour réserver votre premier rendez-vous !',
    'dashboard.explore': 'Explorer les Coiffeurs',
    'dashboard.review.write': 'Écrire un Avis',
    'dashboard.review.rate': 'Évaluez Votre Expérience',
    'dashboard.review.submit': 'Soumettre l\'Avis',
    'dashboard.view.profile': 'Voir le Profil',
    'dashboard.services.management': 'Gestion des Services',
    'dashboard.services.desc': 'Gérez vos services et tarifs',
    'dashboard.service.add': 'Ajouter un Service',
    'dashboard.service.edit': 'Modifier le Service',
    'dashboard.service.update': 'Mettre à jour le Service',
    'dashboard.service.name.ar': 'Nom du Service (Arabe)',
    'dashboard.service.name.en': 'Nom du Service (Anglais)',
    'dashboard.service.name.fr': 'Nom du Service (Français)',
    'dashboard.service.desc.ar': 'Description (Arabe)',
    'dashboard.service.desc.en': 'Description (Anglais)',
    'dashboard.service.desc.fr': 'Description (Français)',
    'dashboard.service.price': 'Prix (DZD)',
    'dashboard.service.duration': 'Durée (minutes)',
    'dashboard.tabs.services': 'Services',
    'dashboard.tabs.bookings': 'Réservations',
    'dashboard.tabs.profile': 'Profil & QR',
    'dashboard.tabs.finance': 'Finances',
    'dashboard.services.empty': 'Aucun service pour le moment',
    'dashboard.services.first': 'Ajouter Votre Premier Service',
    'dashboard.requests.online': 'Demandes en Ligne',
    'dashboard.requests.empty': 'Auncun rendez-vous pour le moment.',
    'dashboard.requests.accept': 'Accepter',
    'dashboard.requests.reject': 'Rejeter',
    'dashboard.requests.complete': 'Marquer comme Terminé',
    'dashboard.payment.online': 'Payé en Ligne',
    'dashboard.payment.salon': 'Payer au Salon',
    'dashboard.walkin.title': 'Réservation sans rendez-vous',
    'dashboard.walkin.desc': 'Ajouter des rendez-vous pour des clients hors plateforme',
    'dashboard.walkin.add': 'Ajouter un Rendez-vous',
    'dashboard.qr.title': 'Code QR de Votre Salon',
    'dashboard.qr.desc': 'Partagez ce code QR dans votre salon pour des réservations rapides',
    'dashboard.gallery.title': 'Galerie de Travaux',
    'dashboard.gallery.desc': 'Téléchargez des photos et vidéos pour attirer plus de clients',
    'dashboard.gallery.upload': 'Télécharger Photo/Vidéo',
    'dashboard.finance.earnings': 'Revenus Totaux',
    'dashboard.finance.expenses': 'Dépenses Totales',
    'dashboard.finance.profit': 'Bénéfice Net',
    'dashboard.finance.add': 'Ajouter une Dépense',
    'dashboard.finance.expense.desc': 'Suivez vos fournitures, le loyer et les dépenses quotidiennes.',
    'dashboard.finance.expense.name': 'Nom de la Dépense',
    'dashboard.finance.expense.amount': 'Montant (DZD)',
    'dashboard.finance.weekly': 'Revenus Hebdomadaires',
    'dashboard.finance.recent': 'Dépenses Récentes',

    // Notifications
    'notification.upcoming.30m': 'Rendez-vous dans 30 minutes!',
    'notification.upcoming.15m': 'Rendez-vous dans 15 minutes!',
    'notification.upcoming.msg': 'Vous avez un rendez-vous prévu avec',
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.explore': 'استكشف',
    'nav.bookings': 'حجوزاتي',
    'nav.account': 'حسابي',
    'nav.signin': 'تسجيل الدخول',
    'nav.signup': 'إنشاء حساب',
    'nav.signout': 'تسجيل الخروج',
    'nav.profile': 'الملف الشخصي',

    // Hero Section
    'hero.title': 'احجز موعدك مع أفضل الحلاقين',
    'hero.description': 'اكتشف الحلاقين القريبين منك، شاهد أعمالهم، واحجز موعدك بسهولة',
    'hero.search.salon': 'ابحث عن حلاق أو صالون...',
    'hero.search.location': 'المدينة أو المنطقة',
    'hero.search.button': 'ابحث الآن',
    'hero.search.nearby': 'الحلاقين القريبين مني',

    // Filters
    'filters.title': 'الفلاتر',
    'filters.location': 'الموقع',
    'filters.location.placeholder': 'أدخل المدينة أو المنطقة',
    'filters.quick': 'فلاتر سريعة',
    'filters.nearby': 'قريب مني',
    'filters.open': 'مفتوح الآن',
    'filters.rated': 'الأعلى تقييماً',
    'filters.vip': 'خدمة VIP',
    'filters.gender': 'نوع الصالون',
    'filters.services': 'الخدمات',
    'filters.price': 'نطاق السعر',
    'filters.rating': 'الحد الأدنى للتقييم',
    'filters.apply': 'تطبيق الفلاتر',
    'filters.clear': 'مسح الكل',
    'filter.all': 'جميع الصالونات',
    'filter.men': 'صالونات الرجال',
    'filter.women': 'صالونات النساء',
    'filter.unisex': 'صالونات مختلطة',
    'filter.open': 'مفتوح الآن',
    'filter.vip': 'VIP فقط',
    'filter.sort': 'ترتيب حسب المسافة',

    // Salon Cards
    'salon.vip': 'VIP',
    'salon.open': 'مفتوح حتى',
    'salon.closed': 'مغلق',
    'salon.men': 'رجال',
    'salon.women': 'نساء',
    'salon.mixed': 'مختلط',
    'salon.starting': 'ابتداءً من',
    'salon.next': 'التوفر التالي',
    'salon.book': 'احجز الآن',
    'salon.details': 'عرض التفاصيل',
    'salon.gallery': 'معرض الأعمال',

    // Salon Grid
    'grid.title': 'اكتشف',
    'grid.title.highlight': 'الصالونات المميزة',
    'grid.description': 'اعثر على الصالون المثالي بالقرب منك. خدمات مهنية، مصففين خبراء.',
    'grid.found': 'صالون موجود',
    'grid.sorted': 'مرتب حسب: المسافة',
    'grid.load': 'تحميل المزيد من الصالونات',

    // Payment Methods
    'payment.title': 'طرق الدفع',
    'payment.baridi': 'بريدي موب',
    'payment.baridi.desc': 'الدفع عبر الهاتف الجزائري',
    'payment.visa': 'بطاقة فيزا',
    'payment.mastercard': 'ماستركارد',
    'payment.card.desc': 'الدفع ببطاقة دولية',
    'payment.paypal': 'باي بال',
    'payment.paypal.desc': 'دفع آمن عبر الإنترنت',
    'payment.after': 'ادفع بعد الخدمة',
    'payment.after.desc': 'دفع نقدي بعد الحلاقة',
    'payment.select': 'اختر طريقة الدفع',

    // Footer
    'footer.about': 'من نحن',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الخدمة',
    'footer.contact': 'اتصل بنا',
    'footer.download': 'تحميل التطبيق',
    'footer.rights': 'جميع الحقوق محفوظة',
    'footer.description': 'منصتك الموثوقة لخدمات الحلاقة والتجميل المهنية',

    // App Download
    'download.title': 'حمل تطبيقنا',
    'download.subtitle': 'احجز مواعيدك أثناء التنقل',
    'download.android': 'متوفر على جوجل بلاي',
    'download.ios': 'حمله من آب ستور',
    'download.description': 'استمتع بحجز سلس مع تطبيقنا المحمول. متاح لأندرويد و iOS.',

    // Authentication
    'auth.welcome': 'مرحباً بك في barberlinkshop',
    'auth.subtitle': 'تواصل مع حلاقين محترفين',
    'auth.signin': 'تسجيل الدخول',
    'auth.signup': 'إنشاء حساب',
    'auth.email': 'البريد الإلكتروني',
    'auth.email.placeholder': 'أدخل بريدك الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.password.placeholder': 'أدخل كلمة المرور',
    'auth.fullname': 'الاسم الكامل',
    'auth.fullname.placeholder': 'أدخل اسمك الكامل',
    'auth.phone': 'رقم الهاتف',
    'auth.phone.placeholder': 'أدخل رقم هاتفك',
    'auth.usertype': 'أنا',
    'auth.usertype.customer': 'زبون',
    'auth.usertype.barber': 'حلاق',
    'auth.loading': 'جاري التحميل...',
    'auth.error': 'خطأ في المصادقة',
    'auth.signup.success': 'تم إنشاء الحساب بنجاح',
    'auth.signup.success.desc': 'مرحباً بك في barberlinkshop!',

    // Barber Profile
    'barber.notfound': 'الحلاق غير موجود',
    'barber.homevisit': 'زيارة منزلية',
    'barber.book': 'حجز موعد',
    'barber.whatsapp': 'واتساب',
    'barber.favorite': 'المفضلة',
    'barber.share': 'مشاركة',
    'barber.services': 'الخدمات',
    'barber.gallery': 'المعرض',
    'barber.reviews': 'التقييمات',
    'barber.minutes': 'دقيقة',
    'salon.staff': 'الحلاقين والكراسي',
    'staff.book': 'حجز موعد مع',
    'booking.notspecified': 'أي حلاق متاح',
    'currency': 'دج',
    'loading': 'جاري التحميل...',
    'error': 'خطأ',

    // Services
    'service.haircut': 'حلاقة الشعر',
    'service.beard': 'حلاقة اللحية',
    'service.kids': 'حلاقة الأطفال',
    'service.shave': 'حلاقة تقليدية',
    'service.coloring': 'صبغ الشعر',
    'service.styling': 'تصفيف الشعر',
    'service.keratin': 'كيراتين',
    'service.protein': 'بروتين',
    'service.facial': 'علاج الوجه',
    'service.massage': 'تدليك الرأس',
    'service.home': 'خدمة كبار الشخصيات',

    // Salon Types
    'salon.type.men': 'رجالي',
    'salon.type.women': 'نسائي',
    'salon.type.unisex': 'مختلط',

    // Contact
    'contact.call': 'اتصال',
    'contact.whatsapp': 'واتساب',
    'contact.chat': 'دردشة الآن',
    'store.title': 'المتجر',
    'store.buy': 'شراء الآن',
    'store.comingsoon': 'قريباً',
    'store.desc': 'خدمة الدفع في المتجر غير مفعلة بالكامل بعد!',

    // Pricing
    'pricing.title': 'اختر باقة الاشتراك المناسبة لك',
    'pricing.subtitle': 'سجل الآن واحصل على الشهر الأول مجاناً!',
    'pricing.monthly': 'شهرياً',
    'pricing.dzd': 'دج',
    'pricing.month': '/شهر',
    'pricing.basic.name': 'الباقة الأساسية',
    'pricing.basic.desc': 'مثالية للحلاقين والمهنيين المستقلين.',
    'pricing.basic.price': '1000',
    'pricing.basic.f1': 'تلقي حجوزات غير محدودة',
    'pricing.basic.f2': 'إدارة الزبائن',
    'pricing.basic.f3': 'معرض أعمال أساسي',
    'pricing.basic.f4': 'إرسال إشعارات وتنبيهات للزبائن',
    'pricing.pro.name': 'باقة المحترفين',
    'pricing.pro.desc': 'لصالونات الحلاقة والتجميل المتنامية.',
    'pricing.pro.price': '2500',
    'pricing.pro.f1': 'كل مميزات الباقة الأساسية',
    'pricing.pro.f2': 'متجر رقمي متكامل لبيع المنتجات',
    'pricing.pro.f3': 'مساعد الذكاء الاصطناعي لاختيار التسريحات والميكاب',
    'pricing.pro.f4': 'تقارير مالية أسبوعية عن الأرباح والأعباء',
    'pricing.premium.name': 'الباقة الممتازة',
    'pricing.premium.desc': 'أدوات متقدمة للأتمتة الشاملة للصالون.',
    'pricing.premium.price': '5000',
    'pricing.premium.f1': 'كل مميزات باقة المحترفين',
    'pricing.premium.f2': 'ظهور كـ VIP في واجهة البحث',
    'pricing.premium.f3': 'إدارة فريق العمل، الكراسي، والصلاحيات',
    'pricing.premium.f4': 'تقارير وفواتير شهرية مفصلة وتلقائية',
    'pricing.button.start': 'ابدأ شهرك المجاني الآن',

    // Testimonials
    'testi.title': 'ماذا يقول عملاؤنا عنا',
    'testi.sub': 'انضم إلى الآلاف من أصحاب الصالونات والمستخدمين الراضين.',
    'testi.1.text': 'منصة barberlinkshop غيرت طريقة عملي بالكامل! أداة الذكاء الاصطناعي جراف العديد من الزبونات لصالون التجميل الخاص بي، والتقارير الأسبوعية الآلية توفر علي الكثير من الوقت.',
    'testi.1.name': 'سارة ل.',
    'testi.1.role': 'مالكة صالون تجميل',
    'testi.2.text': 'أدير صالوناً بـ 4 كراسي. المنصة تنظم الحجوزات بشكل مذهل، وتجعل الزبون يختار مقاله المفضل، وتقوم بإرسال رسائل التنبيه تلقائياً للزبائن دون تدخلي.',
    'testi.2.name': 'أحمد ب.',
    'testi.2.role': 'حلاق محترف',
    'testi.3.text': 'كزبون، أحببت كثيراً سهولة العثور على صالون مناب واختيار الحلاق الخاص بي داخل الصالون عبر التطبيق، كما أمكنني شراء أدوات العناية باللحية من متجر الصالون الرقمي مباشرة.',
    'testi.3.name': 'كريم م.',
    'testi.3.role': 'زبون',

    // AI Stylist
    'ai.stylist.title': 'مساعد الذكاء الاصطناعي للتسريحات والميكاب',
    'ai.stylist.desc': 'قم برفع صورتك وسيقوم الذكاء الاصطناعي باقتراح أفضل التسريحات والميكاب المخصص خصيصاً ليناسب ملامح وجهك!',
    'ai.stylist.upload': 'ارفع صورتك',
    'ai.stylist.men': 'رجال (قصات شعر ولحية)',
    'ai.stylist.women': 'نساء (تسريحات، ميكاب، عناية)',
    'ai.stylist.generate': 'اكتشف الستايل المناسب لي',
    'ai.stylist.result': 'هذه هي الاقتراحات المخصصة لك:',
    'ai.keratin': 'علاجات الكيراتين والبروتين',
    'ai.coloring': 'صبغات الشعر وخصلات الإضاءة',
    'ai.makeup': 'ميكاب احترافي وعناية بالبشرة',

    // Theme
    'theme.light': 'الوضع الفاتح',
    'theme.dark': 'الوضع الداكن',
    'theme.toggle': 'تبديل الوضع',

    // Booking Modal
    'booking.title': 'حجز موعد',
    'booking.service': 'اختر الخدمة',
    'booking.service.select': 'اختر خدمة',
    'booking.service.none': 'لم يتم اختيار خدمة',
    'booking.date': 'اختر التاريخ',
    'booking.date.select': 'اختر تاريخاً',
    'booking.time': 'اختر الوقت',
    'booking.payment': 'طريقة الدفع',
    'booking.total': 'المجموع',
    'booking.confirm': 'تأكيد الحجز',
    'booking.cancel': 'إلغاء',
    'payment.electronic': 'الدفع الإلكتروني',
    'payment.after.visit': 'الدفع عند الحضور',
    'salon.reviews': 'تقييم',

    // Dashboards & Profiles
    'dashboard.title.customer': 'حجوزاتي',
    'dashboard.title.barber': 'لوحة تحكم الحلاق',
    'dashboard.customer.empty': 'ليس لديك أي حجوزات بعد. اكتشف الحلاقين لحجز موعدك الأول!',
    'dashboard.explore': 'اكتشف الحلاقين',
    'dashboard.review.write': 'اكتب تقييم',
    'dashboard.review.rate': 'قيم تجربتك',
    'dashboard.review.submit': 'إرسال التقييم',
    'dashboard.view.profile': 'عرض الملف',
    'dashboard.services.management': 'إدارة الخدمات',
    'dashboard.services.desc': 'إدارة خدماتك وأسعارك',
    'dashboard.service.add': 'إضافة خدمة',
    'dashboard.service.edit': 'تعديل الخدمة',
    'dashboard.service.update': 'تحديث الخدمة',
    'dashboard.service.name.ar': 'اسم الخدمة (بالعربية)',
    'dashboard.service.name.en': 'اسم الخدمة (بالإنجليزية)',
    'dashboard.service.name.fr': 'اسم الخدمة (بالفرنسية)',
    'dashboard.service.desc.ar': 'الوصف (بالعربية)',
    'dashboard.service.desc.en': 'الوصف (بالإنجليزية)',
    'dashboard.service.desc.fr': 'الوصف (بالفرنسية)',
    'dashboard.service.price': 'السعر',
    'dashboard.service.duration': 'المدة (بالدقائق)',
    'dashboard.tabs.services': 'الخدمات',
    'dashboard.tabs.bookings': 'الحجوزات',
    'dashboard.tabs.profile': 'الملف الشخصي و رمز الاستجابة',
    'dashboard.tabs.finance': 'المالية',
    'dashboard.services.empty': 'لا توجد خدمات حتى الآن',
    'dashboard.services.first': 'أضف خدمتك الأولى',
    'dashboard.requests.online': 'الطلبات عبر الإنترنت',
    'dashboard.requests.empty': 'لا توجد مواعيد حتى الآن.',
    'dashboard.requests.accept': 'قبول',
    'dashboard.requests.reject': 'رفض',
    'dashboard.requests.complete': 'تحديد كمكتمل',
    'dashboard.payment.online': 'تم الدفع أونلاين',
    'dashboard.payment.salon': 'الدفع في الصالون',
    'dashboard.walkin.title': 'الحجز اليدوي المباشر',
    'dashboard.walkin.desc': 'أضف مواعيد للعملاء المباشرين غير المسجلين بالمنصة',
    'dashboard.walkin.add': 'إضافة موعد مباشر',
    'dashboard.qr.title': 'رمز الاستجابة السريع للصالون',
    'dashboard.qr.desc': 'شارك هذا الرمز في صالونك لحجوزات أسرع',
    'dashboard.gallery.title': 'معرض الأعمال',
    'dashboard.gallery.desc': 'ارفع صوراً ومقاطع فيديو لأفضل أعمالك لجذب المزيد من الزبائن',
    'dashboard.gallery.upload': 'رفع صورة/فيديو',
    'dashboard.finance.earnings': 'إجمالي الأرباح',
    'dashboard.finance.expenses': 'إجمالي المنصرفات',
    'dashboard.finance.profit': 'صافي الربح',
    'dashboard.finance.add': 'إضافة منصرف جديد',
    'dashboard.finance.expense.desc': 'تتبع لوازم الحلاقة، إيجار الصالون والمنصرفات اليومية.',
    'dashboard.finance.expense.name': 'اسم المنصرف',
    'dashboard.finance.expense.amount': 'المبلغ',
    'dashboard.finance.weekly': 'الأرباح الأسبوعية',
    'dashboard.finance.recent': 'المنصرفات الأخيرة',

    // Notifications
    'notification.upcoming.30m': 'موعدك بعد 30 دقيقة!',
    'notification.upcoming.15m': 'موعدك بعد 15 دقيقة!',
    'notification.upcoming.msg': 'لديك موعد مقرر مع',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en'); // Default to English

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && ['en', 'fr', 'ar'].includes(savedLang)) {
      setLanguage(savedLang);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};